export interface I_Process {
    est_conv: number,
    fase_actual: string,
    id_fase: number,
    id_conv: number,
    id_prog: null | number,
    id_tcond: number,
    marc_temp: string,
    marc_update: string,
    nomb_conv: string,
    programa: null | string,
    tipo_cond: string,
    porcentaje: number,
    sede: string,
}